#!/bin/bash 

#SBATCH --job-name=test             # Job name
#SBATCH --account=akuronen          # Billing project, has to be defined!
#SBATCH --time=10:00                # Max. duration of the job
#SBATCH --mem-per-cpu=1000M         # Memory to reserve per core
#SBATCH --partition=test            # Job queue (partition)
#SBATCH --tasks=4                   # Number of cores
#SBATCH --output=out_%j
#SBATCH --error=err_%j

# For GNU+OpenMPI
module load gcc openmpi
# For Intel:
# module load intel-oneapi-compilers/2022.1.0 intel-oneapi-mpi/2021.6.0

srun mpiexample

